const wordData = [
  { word: "翻", pinyin: "guang", meaning: "to stroll; to browse (shops/market)" },
  { word: "頁", pinyin: "huran", meaning: "suddenly" },
  { word: "三明治", pinyin: "xiaochi", meaning: "snack; street food" },
  { word: "門", pinyin: "chukou", meaning: "exit" },
  { word: "課堂", pinyin: "gang", meaning: "just; a short while ago" },
  { word: "期末", pinyin: "xing", meaning: "surname; family name" },
  { word: "口試", pinyin: "jiu", meaning: "then; right away; as early as" },
  { word: "篇", pinyin: "ge", meaning: "each; every" },
  { word: "作文", pinyin: "shajia", meaning: "to bargain; to haggle" },
  { word: "用功", pinyin: "zhaopai", meaning: "signboard; signature (dish/product)" },
  { word: "當", pinyin: "youke", meaning: "tourist; visitor" },
  { word: "修", pinyin: "doufu", meaning: "tofu" },
  { word: "教授", pinyin: "zha", meaning: "to deep-fry; fried" },
  { word: "知識", pinyin: "jipai", meaning: "chicken cutlet" },
  { word: "豐富", pinyin: "xiang", meaning: "fragrant; tasty; aromatic" },
  { word: "教法", pinyin: "xiguan", meaning: "habit; to be used to" },
  { word: "系", pinyin: "tang", meaning: "sugar" },
  { word: "文法", pinyin: "xuan", meaning: "to choose; select" },
  { word: "筆試", pinyin: "wu", meaning: "no; none; without" },
  { word: "交", pinyin: "jia", meaning: "to add" },
  { word: "報告", pinyin: "bingkuai", meaning: "ice cubes" },
  { word: "認真", pinyin: "tuijian", meaning: "to recommend; recommendation" },
  { word: "字典", pinyin: "la", meaning: "spicy; hot (taste)" },
  { word: "翻", pinyin: "suan", meaning: "sour" },
  { word: "題", pinyin: "xian", meaning: "salty" },
  { word: "努力", pinyin: "ku", meaning: "bitter" },
  { word: "能力", pinyin: "wen", meaning: "to smell; to sniff" },
  { word: "將來", pinyin: "taoyan", meaning: "to dislike; annoying" },
  { word: "夠", pinyin: "qishi", meaning: "actually; in fact" },
  { word: "加油", pinyin: "shi", meaning: "to try; to taste" },
  { word: "義大利", pinyin: "choudoufu", meaning: "stinky tofu" },
  { word: "期末考", pinyin: "ezaijian", meaning: "oyster omelet" },
  { word: "翻", pinyin: "tebie", meaning: "special; especially; unusual" }
];
